# Generated by Django 5.2.8 on 2025-11-14 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='base.vendor'),
        ),
    ]
